### PR TITLE
Adding text cluster explanation form

### PR DESCRIPTION
**Pull request by charyeezy**
Updating text cluster explanation as form

from these docs here  https://relevanceai.readthedocs.io/en/latest/operations/cluster/explain_text_clusters.html

Please test here

- [Cluster Text Explanation](https://colab.research.google.com/github/RelevanceAI/workflows/blob/feature/sdk-429-explain-text-clusters-as-form/workflows/explain-text-clusters/explain-text-clusters_form.ipynb#scrollTo=QWINwj0FQtJN)

### CODE REVIEW

**Comment by boba-and-beer** [comment]
The pre-requisite should be that they clustered already. This should only be used once you have run the cluster workflow.

**Comment by boba-and-beer** [comment]
Also needs to default to form.

**Comment by charyeezy** [comment]
I have cleaned the form now ~ 

- hidden form by default
- removed `ds.cluster` - loads `ClusterOps` with given `alias` and `vector_field`
```
  cluster_ops = ds.ClusterOps(
      alias = cluster_alias, 
      vector_fields = [vector_field]
  )
  cluster_ops.create_centroids()
```
- Creates centroids in case not exist
```
cluster_ops.create_centroids()
```

Awaiting on `operations` to be changed to `operations_new` to test - https://linear.app/relevance/issue/SDK-447/change-all-operations-to-operations-new

**Comment by boba-and-beer** [comment]
Good work - thank you.

**Pull request merged**
